// Polyfills must run before the OpenNext worker loads Next's server chunks.
import "./worker-polyfills";

// Generated by `opennextjs-cloudflare build`; absent on fresh checkout, so
// the type-checker needs @ts-ignore here.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated at build time
import { default as handler } from "./.open-next/worker.js";

export default handler;

// Re-export required if the app uses the DO queue / tag cache (ISR on Workers).
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore generated at build time
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";